export const NAMES = {
	sheets: {
		createMenu: "createMenuSheet",
		createTraining: "createTrainingSheet",
		createFromRoutine: "createFromRoutineSheet",
		addRoutine: "addRoutineSheet",
		createGoals: "createGoalsSheet",
		trainingRoutine: "trainingRoutineSheet",
		muscleGroupDropdown: "muscleGroupDropdownSheet",
		filterDropdown: "filterDropdownSheet",
		exercisePicker: "exercisePickerSheet",
		addFilter: "addFilterSheet",
		addNewExercise: "addNewExerciseSheet",
		addNewExerciseFromPicker: "addNewExerciseFromPickerSheet",
		editGoals: "editGoalsSheet",
		editExercise: "editExerciseSheet",
		editFilter: "editFilterSheet",
		editRoutine: "editRoutineSheet",
		routineMenu: "routineMenuSheet",
		routineActions: "routineActionsSheet",
		routineAddExercise: "routineAddExerciseSheet",
		routineEditNote: "routineEditNoteSheet",
		editTraining: "editTrainingSheet",
		trainingEditMenu: "trainingEditMenuSheet",
		trainingActions: "trainingActionsSheet",
		trainingAddExercise: "trainingAddExerciseSheet",
		trainingAddSet: "trainingAddSetSheet",
		trainingEditNote: "trainingEditNoteSheet",
		trainingEditSet: "trainingEditSetSheet",
		exerciseHistory: "exerciseHistorySheet",
		colorPicker: "colorPickerSheet",
		deleteRoutine: "deleteRoutineSheet",
		deleteTraining: "deleteTrainingSheet",
	},
} as const;
