export const NAMES = {
	sheets: {
		createMenu: "createMenuSheet",
		createTraining: "createTrainingSheet",
		createFromRoutine: "createFromRoutineSheet",
		addRoutine: "addRoutineSheet",
		createGoals: "createGoalsSheet",
		trainingRoutine: "trainingRoutineSheet",
		muscleGroupDropdown: "muscleGroupDropdownSheet",
		filterDropdown: "filterDropdownSheet",
		exercisePicker: "exercisePickerSheet",
		addFilter: "addFilterSheet",
		addNewExercise: "addNewExerciseSheet",
		addNewExerciseFromPicker: "addNewExerciseFromPickerSheet",
		editGoals: "editGoalsSheet",
		editExercise: "editExerciseSheet",
		editFilter: "editFilterSheet",
		editRoutine: "editRoutineSheet",
		editTraining: "editTrainingSheet",
		deleteRoutine: "deleteRoutineSheet",
		deleteTraining: "deleteTrainingSheet",
	},
} as const;
